---
Name: edit-in-sitetree-button
After:
  - '#coreconfig'
---

SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    - Sunnysideup\EditeInSiteTreeButton\Extension\EditInSiteTreeButtonMaker
